site_name: Stochastic Tangents

theme:
    name: 'material'
    icon:
      logo: material/home 
    
    features:
      - content.footnote.tooltips
      
    palette:

    # # Light mode
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   primary: black 
    #   accent: blue
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode

    # # Dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: white
    #   accent: blue
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode

      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: black
        accent: blue
        toggle:
          icon: material/brightness-2
          name: Switch to light mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: white
        accent: blue
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
 


extra:
  homepage: https://lakhabishal.com/

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - glightbox
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

extra_css:
  - stylesheets/theme.css

